### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by lem0nb** [ijjk/notion-blog#77]
Deployment failed with error.

Fetching Source Code
6s

Skipping Build Cache
3s

Building
22:59:14.714
Installing dependencies...
22:59:15.021
yarn install v1.22.11
22:59:15.114
[1/4] Resolving packages...
22:59:15.347
[2/4] Fetching packages...
22:59:27.641
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
22:59:27.642
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
22:59:27.652
[3/4] Linking dependencies...
22:59:27.654
warning " > @zeit/react-jsx-parser@2.0.0" has incorrect peer dependency "react@^16.8.3".
22:59:27.654
warning " > @zeit/react-jsx-parser@2.0.0" has incorrect peer dependency "react-dom@^16.8.3".
22:59:31.860
[4/4] Building fresh packages...
22:59:32.052
Done in 17.04s.
22:59:32.073
Detected Next.js version: 10.2.0
22:59:32.075
Running "yarn run build"
22:59:32.418
yarn run v1.22.11
22:59:32.462
$ next build && node .next/server/build-rss.js
22:59:32.887
info  - Loaded env from /vercel/path0/.env
22:59:33.514
22:59:33.514
> Build error occurred
22:59:33.516
Error: 
22:59:33.516
NOTION_TOKEN is missing from env, this will result in an error
22:59:33.516
Make sure to provide one before starting Next.js
22:59:33.516
    at warnOrError (/vercel/path0/next.config.js:23:15)
22:59:33.516
    at Object.<anonymous> (/vercel/path0/next.config.js:29:3)
22:59:33.517
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
22:59:33.517
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
22:59:33.517
    at Module.load (internal/modules/cjs/loader.js:937:32)
22:59:33.517
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
22:59:33.517
    at Module.require (internal/modules/cjs/loader.js:961:19)
22:59:33.517
    at require (internal/modules/cjs/helpers.js:92:18)
22:59:33.517
    at loadConfig (/vercel/path0/node_modules/next/dist/next-server/server/config.js:8:72)
22:59:33.517
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
22:59:33.533
error Command failed with exit code 1.
22:59:33.533
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:59:33.553
Error: Command "yarn run build" exited with 1

**Comment by ijjk** [comment]
Hi, it looks like the `NOTION_TOKEN` value wasn't provided during set-up, please make sure it is populated while deploying.
