### ISSUE TITLE
Vercel build errors

### ISSUE THREAD

**Issue by shenoynikhil** [ijjk/notion-blog#91]
I am getting build errors in vercel,

```


https://github.com/browserslist/browserslist#browsers-data-updating
--
20:05:23.388 | node:internal/crypto/hash:71
20:05:23.388 | this[kHandle] = new _Hash(algorithm, xofLen);
20:05:23.388 | ^
20:05:23.388 |  
20:05:23.389 | Error: error:0308010C:digital envelope routines::unsupported
20:05:23.389 | at new Hash (node:internal/crypto/hash:71:19)
20:05:23.389 | at BulkUpdateDecorator.hashFactory (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
20:05:23.389 | at BulkUpdateDecorator.update (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
20:05:23.389 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
20:05:23.389 | at processTicksAndRejections (node:internal/process/task_queues:82:21)
20:05:23.389 | at runNextTicks (node:internal/process/task_queues:64:3)
20:05:23.389 | at process.processImmediate (node:internal/timers:442:9) {


```

What could be a solution?

**Comment by pabloalexandrino** [comment]
Downgrade node version in vercel

**Comment by shenoynikhil** [comment]
Thanks! it worked.
