### ISSUE TITLE
OpenSSL / digital envelope routine

### ISSUE THREAD

**Issue by biggeye** [ijjk/notion-blog#95]
Thrown during deployment through Vercel:

<code>
Error: error:0308010C:digital envelope routines::unsupported
--
10:02:37.169 | at new Hash (node:internal/crypto/hash:71:19)
10:02:37.169 | at Object.createHash (node:crypto:133:10)
10:02:37.169 | at BulkUpdateDecorator.hashFactory (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
10:02:37.169 | at BulkUpdateDecorator.update (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
10:02:37.169 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
10:02:37.169 | at processTicksAndRejections (node:internal/process/task_queues:82:21)
10:02:37.169 | at runNextTicks (node:internal/process/task_queues:64:3)
10:02:37.169 | at process.processImmediate (node:internal/timers:442:9) {
10:02:37.169 | opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
10:02:37.169 | library: 'digital envelope routines',
10:02:37.169 | reason: 'unsupported',
10:02:37.170 | code: 'ERR_OSSL_EVP_UNSUPPORTED'
10:02:37.170 | }
10:02:37.170 |  
10:02:37.170 | Node.js v18.13.0
10:02:37.194 | error Command failed with exit code 1.
10:02:37.195 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:02:37.213 | Error: Command "yarn run build" exited with 1
10:02:37.898 | BUILD_FAILED: Command "yarn run build" exited with 1
</code>

**Comment by mahomiyata** [comment]
Hi, @biggeye 

I got the same error, which seems to occur when you use Node.js v18.
You won't get this error if you use Node.js v16 when you deploy the project.

You can change the Node.js version from Project Settings on the Vercel console.

**Comment by developerisnow** [comment]
The same error and node v16 doesn't help!

**Comment by Proximat** [comment]
Thank you Mahomiyata, I had the same issue.
I solved it by going to /settings/general and scroll down until you see a dropdown to change Node v18 to v16

**Comment by luismqueral** [comment]
I am also getting a similar error.

For what it's worth, I've set the Node version to v16 and I've manually connected my page to the vercel connection (which is something that I saw buried in the Notion docs, thinking this was a API / Permission issue.


<img width="649" alt="Screen Shot 2023-05-02 at 6 17 23 PM" src="https://user-images.githubusercontent.com/3460146/235800202-1742f48c-dec4-428a-a052-01fdd7fa27b6.png">

```Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error
--
18:10:06.617 | Error: Notion API error (401)
18:10:06.618 | {"date":["Tue, 02 May 2023 22:10:06 GMT"],"content-type":["application/json; charset=utf-8"],"content-length":["114"],"connection":["close"],"set-cookie":["notion_browser_id=3b4f4175-a3f7-4c43-a17d-512f782e2f1a; Domain=www.notion.so; Path=/; Expires=Wed, 01 May 2024 22:10:06 GMT; Secure","notion_check_cookie_consent=false; Domain=www.notion.so; Path=/; Expires=Wed, 03 May 2023 22:10:06 GMT; Secure","__cf_bm=MjegbTKfSzYhiGaPGqWxApQIQ7ie1eDIN2rKko0U.D4-1683065406-0-Ae+IQHepI0Dle0NitfYVbr+NlzGU4LuF8WrC0F97Eeq4oIPd8ZOYSFrdB6EoOJvk/I4/o5E2XbJ1BfVb49Jw6hU=; path=/; expires=Tue, 02-May-23 22:40:06 GMT; domain=.notion.so; HttpOnly; Secure; SameSite=None","_cfuvid=kPmIXO_Gejh3KF7Z8JhP7DlhOPkD8.IBgAaIbSp2m7Q-1683065406609-0-604800000; path=/; domain=.notion.so; HttpOnly; Secure; SameSite=None"],"content-security-policy":["default-src 'none'"],"x-dns-prefetch-control":["off"],"x-frame-options":["SAMEORIGIN"],"strict-transport-security":["max-age=5184000; includeSubDomains"],"x-download-options":["noopen"],"x-content-type-options":["nosniff"],"x-permitted-cross-domain-policies":["none"],"referrer-policy":["strict-origin-when-cross-origin"],"x-xss-protection":["0"],"etag":["W/\"72-qlnQkLc81he+5iGNdLO8x1lGLCk\""],"vary":["Accept-Encoding"],"cf-cache-status":["DYNAMIC"],"server":["cloudflare"],"cf-ray":["7c1397a6aed72256-ORD"]}
18:10:06.619 | {"errorId":"8d2e94c3-5d02-40fc-bb5d-00324367fef6","name":"UnauthorizedError","message":"Could not decrypt token."}
18:10:06.621 | at rpc (/vercel/path0/.next/server/chunks/98.js:38:11)
18:10:06.621 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:10:06.622 | at async getStaticProps (/vercel/path0/.next/server/pages/blog.js:61:7)
18:10:06.622 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:329:24)
18:10:06.622 | at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
18:10:06.622 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
18:10:06.622 |  
18:10:06.622 | > Build error occurred
18:10:06.622 | info  - Generating static pages (6/6)
18:10:06.624 | Error: Export encountered errors on following paths:
18:10:06.624 | /blog
18:10:06.624 | at /vercel/path0/node_modules/next/dist/export/index.js:487:19
18:10:06.624 | at runMicrotasks (<anonymous>)
18:10:06.624 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:10:06.624 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
18:10:06.624 | at async /vercel/path0/node_modules/next/dist/build/index.js:833:17
18:10:06.624 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
18:10:06.624 | at async /vercel/path0/node_modules/next/dist/build/index.js:707:13
18:10:06.624 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
18:10:06.624 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
18:10:06.670 | error Command failed with exit code 1.
18:10:06.670 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:10:06.688 | Error: Command "yarn run build" exited with 1
18:10:07.388 | Deployment completed
18:10:07.010 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1```

**Comment by 00dionizio** [comment]
i had the same error `yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\workspace\notion-blog\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138971:18)
    at BulkUpdateDecorator.update (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138872:50)
    at OriginalSource.updateHash (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack-sources3\index.js:1:10264)
    at NormalModule._initBuildHash (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68468:17)
    at handleParseResult (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68534:10)
    at C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68628:4
    at processResult (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68343:11)
    at C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68407:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138971:18)
    at BulkUpdateDecorator.update (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138872:50)
    at OriginalSource.updateHash (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack-sources3\index.js:1:10264)
    at NormalModule._initBuildHash (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68468:17)
    at handleParseResult (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68534:10)
    at C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68628:4
    at processResult (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68343:11)
    at C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68407:5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138971:18)
    at BulkUpdateDecorator.update (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138872:50)
    at OriginalSource.updateHash (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack-sources3\index.js:1:10264)
    at NormalModule._initBuildHash (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68468:17)
    at handleParseResult (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68534:10)
    at C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68628:4
    at processResult (C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68343:11)
    at C:\workspace\notion-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68407:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

solutions?

**Comment by drodol** [comment]
Same error!
I am getting this also:
`Error: Node.js version 16.x has reached End-of-Life. Deployments created on or after 2023-08-15 will fail to build. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.`

**Comment by mhtkoc** [comment]
[Solution for same problem ](https://github.com/ijjk/notion-blog/issues/96#issuecomment-1684910144)
